AI_STRATEGY_PREFILTER_SCORE = 75
AI_DEFAULT_FINAL_BUY_CONVICTION = 75
AI_DEFAULT_FINAL_BUY_LIQUIDITY = True
AI_FUNDAMENTAL_FETCH_LIMIT = 25
AI_LIST_REVIEW_LIMIT = 20
AI_SESSION_CALL_LIMIT = 25

AI_LIST_TOP_N = 10
